#!/bin/bash

FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"

is_docker_running () {
    DOCKER_NAME=""
    if [ -f "$FILE_PATH" ]; then
        DOCKER_NAME=$(cat "$FILE_PATH" | grep "container_name" | awk -F ':' '{print $2}' | xargs)
    fi
    if [ -n "$DOCKER_NAME" ]; then
        docker inspect "$DOCKER_NAME" | grep -q "\"Status\": \"running\"," || return 1
        return 0
    fi
    return 1
}

case $1 in
start)
    # docker application will be started by appcenter
    exit 0
    ;;
stop)
    # docker application will be stopped by appcenter
    exit 0
    ;;
status)
    # exit 0 if running, exit 3 if not running
    if is_docker_running; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac
